# Generated by Django 5.0.4 on 2024-05-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('timecap', models.CharField(max_length=100, null=True)),
                ('descanso', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('fk_evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.evento')),
            ],
        ),
    ]
