# Generated by Django 5.0.4 on 2024-05-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
