# Generated by Django 5.0.4 on 2024-05-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('tipoEvento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidadPartes', models.IntegerField(default=1)),
                ('date_start', models.DateField()),
                ('date_end', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('fk_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria')),
                ('fk_tipoEvento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipoEvento.tipoevento')),
            ],
        ),
    ]
